### ISSUE TITLE
As of 1.0.0 typescript declarations are not included in the built output.

### ISSUE THREAD

**Issue by mintchaos** [bohdanbirdie/vitest-launchdarkly-mock#2] opened 2024-02-13 22:11 UTC
it seems like it should be, as you do have `declaration: true` in your tsconfig, but it's it's not in the output as seeable here https://www.npmjs.com/package/vitest-launchdarkly-mock/v/1.0.0?activeTab=code

So I made my own .d.ts file, but it'd be great to have this included.

Also ty for this package!

**Comment by drwpow** [comment] 2024-02-22 17:27
I believe the issue is in the `package.json`; as of TypeScript 4.7 if `export` is used it needs to have a `"type"` key:

```diff
  "exports": {
    ".": {
      "import": "./dist/index.js",
+     "types": "./dist/index.d.ts",
-   }
+   },
+   "./*": "./*"
  },
```

The last line is optional but makes it easier for consumers to access other files in the package if they need them (by default `export` makes everything private and you have to explicitly allow globs)

**Comment by bohdanbirdie** [comment] 2024-03-14 10:29
@mintchaos @drwpow resolved in https://github.com/bohdanbirdie/vitest-launchdarkly-mock/pull/4

**Closed as completed by bohdanbirdie** 2024-03-14 10:29 UTC
